Fix/headmaster auth
BloomTech-Labs/deprecated-village-book-builders-fe-b pull request #20
Opened 2021-01-05 18:54 UTC by ferror18

Created a new action called refresh token. This action refreshes Redux state whenever there is a refresh and there is a token in local storage.

Included authentication necessary to access protected resources

2021-01-05 19:08 UTC, kima-92 approved these changes

2021-01-05 19:20 UTC, Jahteo requested changes
Only actual change requested is that the login shouldn't use axiosWithAuth. It needs a standard axios. Everything else I like.

2021-01-05 19:20 UTC, Jahteo commented on src/components/App.js
> +        <Route path="/admin" component={AdminDashboard} />
This is definitely cleaner. Like it.

2021-01-05 19:20 UTC, Jahteo commented on src/components/pages/Headmaster/HeadmasterDashboard.js
> +function HeadmasterDashboard({ match }) {
what's match? I'm not seeing it being used, or passed in anywhere.

2021-01-05 19:20 UTC, Jahteo commented on src/components/pages/Headmaster/HeadmasterDashboard.js
> +          <NavLink to={`/mentor-pairings`} onClick={() => setVisible(true)}>
Quotes are better than backticks here, for consistency (&theoretically for a minuscule optimization)

2021-01-05 19:20 UTC, Jahteo commented on src/components/pages/Headmaster/TestComponent.js
> +      <h1>Test Component Page</h1>
Nice semantic change! Thank ya!

2021-01-05 19:20 UTC, Jahteo commented on src/components/pages/Login/Login.js
> +      props.checkToken();
I know you explained this to me already, but does running checkToken also cause it to exit the login page and go to the main pages?

2021-01-05 19:20 UTC, Jahteo commented on src/state/actions/index.js
> +  axiosWithAuth()
Login should use an axios call, not an axiosWithAuth.

axiosWithAuth is for making an axios call where we need authorization headers (for all the protected endpoints). Logging in is the first step to getting that authorization, and should not require that a token already be saved to local storage (which is a what axiosWithAuth does).

2021-01-05 19:20 UTC, Jahteo commented on src/state/reducers/loginReducer.js
> +      console.log(decoded);
minor, minor bit to help the team.
label the comment next time. something like:
console.log("AUTH_SUCCESS decoded ", decoded)

2021-01-05 19:20 UTC, Jahteo commented on src/utils/axiosWithAuth.js
> +    baseURL: process.env.REACT_APP_BASE_URL,
How does this keep getting changed back to BASEURL? I swear we've had to fix it twice already, lol!

2021-01-05 19:39 UTC, ferror18 commented on src/components/App.js
> +        <Route path="/admin" component={AdminDashboard} />
Perfect Ill change that in one asap.

2021-01-05 19:51 UTC, ferror18 commented on src/components/pages/Login/Login.js
> +      props.checkToken();
What happens is that the login route displays either the login comp or the headmaster dashboard depending if loggedIn = false or True but so far it doesn't redirect anywhere is more like a subroute. Either way, It won't cause it to go to the dashboard unless the token is present in which case yes it will.

2021-01-05 22:23 UTC, Jahteo requested changes
Not sure how easy this would be to revert back the mentee/pairing portion, or if I'm thinking things through wrong. Let me know if it makes sense or if you think it should stay the way you have it. 
Thanks for fixing the axios portion. My mentor brought up that it was actually a good thing to remove the baseURL like you did, and if you/we/someone wants to, we can write a mini axiosWithoutAuth util (that holds the baseURL just like axiosWithAuth, but without the header/token parts) to follow the same pattern.

2021-01-05 22:23 UTC, Jahteo commented on src/state/actions/index.js
> +  axios
Thank ya!

2021-01-05 22:23 UTC, Jahteo commented on src/components/pages/Headmaster/HeadmasterDashboard.js
> +          <Route path="/mentee" component={Mentees} />
I think the old pathway was better. The mentor-pairings button on navbar should lead to a page that shows the mentee's, mentors, and ability to pair them. We're only working on the mentee portion, but we need to keep space for the next ones to be added.

I think the better way would be to put the mentee component as a section within the original mentor pairing component

2021-01-05 22:23 UTC, Jahteo commented on src/components/pages/Headmaster/Mentees/Mentees.js
>  import axios from 'axios';
as mentioned earlier, I think we need these as two different components, with the mentee's nested/displayed inside the mentorpairing one. (It might make more sense if we rename the MentorPairing component to something like MentorshipComponent or MentorshipContainer or something that makes it clear that it's a container/route that will hold the mentee/mentors/pairing components

2021-01-06 01:46 UTC, Jahteo approved these changes

2021-01-06 01:46 UTC, merged