added TeacherDashboard.js / setup-teacher profile folders
BloomTech-Labs/deprecated-village-book-builders-fe-b pull request #30
Opened 2021-01-19 21:36 UTC by sunkist5691

2021-01-19 22:00 UTC, RohithSachdeva approved these changes
Good start

2021-01-20 15:53 UTC, joshwhitwell requested changes

2021-01-20 15:53 UTC, joshwhitwell commented on src/components/pages/Teacher/TeacherDashboard.js
> +export default TeacherDashboard;
Was this file duplicated from HeadmasterDashboard.js? It seems like there is a lot of unused  / unnecessary code currently. I would suggest we remove the unused code before merging.

2021-01-20 15:56 UTC, joshwhitwell commented on src/components/pages/Teacher/TeacherDashboard.js
> +import Village from '../Village/Village.component.js';
Do we need to be importing the Village and School forms for the teacher dashboard?

2021-01-20 16:03 UTC, joshwhitwell commented on src/components/pages/Teacher/TeacherDashboard.js
> +  // Todo: this needs to be converted to a mediaquery and removed from here
I would suggest handling the window resizing logic in a separate style sheet using media queries instead of adding event listeners to the window. This will make it easier to debug any styling issues down the road.

2021-01-20 16:04 UTC, joshwhitwell commented on src/components/pages/Teacher/TeacherDashboard.js
> +          </NavLink>
The teachers don't need to have access to the mentor or village pages so probably can remove all the nav links except the teacher profile.

2021-01-20 16:13 UTC, closed without merging