Feature/teacher profile
BloomTech-Labs/deprecated-village-book-builders-fe-b pull request #36
Opened 2021-01-21 22:11 UTC by andre-jeon

- Added TeacherProfile and TeacherProfileFrom for the Teacher Role.
- Added editTeacherProile and fetchTeacherProfile.
- Added FETCH_TEACHER_PROFILE, FETCH_TEACHER_PROFILE_SUCCESS, and FETCH_TEACHER_PROFILE_FAILURE to actionTypes.
- Imported and added FETCH_TEACHER_PROFILE to teacherReducer.js file.

2021-01-21 22:14 UTC, sunkist5691 approved these changes
Looks good so far,

2021-01-25 15:42 UTC, joshwhitwell commented on src/components/pages/Teacher/TeacherProfile/TeacherProfile.js
> +    props.fetchTeacherProfile(1); // change this later with login
This should be changed to pull the current teacher ID from params instead of hard coding into the action arguments.

2021-01-25 15:45 UTC, joshwhitwell commented on src/state/actions/index.js
> +export const editTeacherProfile = (id, data) => dispatch => {
the editTeacherProfile and fetchTeacherProfile were already merged in a previous branch. These duplicate actions should be deleted/merged with the existing ones.

2021-01-25 15:47 UTC, joshwhitwell requested changes
Nice work! It looks like there were duplicate editTeacherProfile and fetchTeacherProfile actions that had already been merged in a previous branch. The duplicates should either deleted or combined with the existing ones before merging the branch.

2021-01-26 15:23 UTC, joshwhitwell approved these changes
Nice job with the changes, looks good!

2021-01-26 15:23 UTC, merged