set up for mentor pairing
BloomTech-Labs/deprecated-village-book-builders-fe-b pull request #48
Opened 2021-01-29 21:27 UTC by sunkist5691

Please don't merge this into MAIN (this is just for the testing purpose)

2021-02-01 21:16 UTC, joshwhitwell requested changes
Great job! Really good work on the MentorPairing component. I noticed you left some commented out promise handlers in the action creators for fetchMentor and fetchMentee. These should be deleted since they are obsolete with the async await syntax.

2021-02-01 21:16 UTC, joshwhitwell commented on src/components/pages/Mentor/MentorPairing.js
> +          eachMentee.availability.as_early_as
This data field on mentees should be "general_availability"

2021-02-01 21:16 UTC, joshwhitwell commented on src/state/actions/index.js
> +  console.log('DID FETCH MENTOR');
The commented promise handlers should be deleted since they are now obsolete with the async await syntax.

2021-02-02 01:13 UTC, sunkist5691 commented on src/components/pages/Mentor/MentorPairing.js
> +          eachMentee.availability.as_early_as
nice catch

2021-02-02 01:16 UTC, sunkist5691 reviewed
changed request:
 "deleting comment of promise handling"
 "change general_availability"

2021-02-02 01:43 UTC, joshwhitwell approved these changes

2021-02-02 02:32 UTC, RohithSachdeva approved these changes
Good job on the mentor pairing

2021-02-02 02:38 UTC, merged